sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t Sakshi-Bajaj/docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true Sakshi-Bajaj/docker-frontend npm run test
